name: alphatims_docs
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - openssl=1.1.1k
  - pip=20.2.4
  - python=3.8.8
  - setuptools=52.0.0
  - sqlite=3.35.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
