name: alphatims_docs
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - libffi
  - ncurses
  - openssl
  - pip=20.2
  - python=3.8
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
